### ISSUE TITLE
[Question] Convert yup schema to yup ast

### ISSUE THREAD

**Issue by pdufour** [demvsystems/yup-ast#31]
Is there a way to convert a yup schema into the array format? I.e. yup.array() -> [yup.array]?

**Comment by kassuro** [comment]
It's a nice idea, not sure about the general usability.

>Another way I was thinking of doing it was adding a method where you could call something like `transfromToAST(yupSchema)` but that involved parsing the schema manually since yup doesn't provide great introspection methods, and seemed error-prone if the yup api ever changed.

You're totally right about the error prone part. Might be the reason the initial author didn't build something for this.

Currently it looks like we will be migrate away from yup to zod, as the generated typescript types look much better. Zod seems to have a good ecosystem as well so maybe you take a look at it. 

So `yup-ast` might go into a maintenance-mode and I won't get much time to work on this in the future (if any).
